spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: ostafon
    password: 0000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
  web:
    error:
      include-message: always
      include-binding-errors: always

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

debug: true

logging:
  level:
    com.ostafon.supportportal.auth: DEBUG
    root: INFO

    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE

    org.flywaydb: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

    com.zaxxer.hikari: DEBUG
